models/ActiveRecord.php
<?php
namespace app\models;

/**
 * Class ActiveRecord
 * @package app\models
 *
 * @property string $id
 */
class ActiveRecord extends \yii\mongodb\ActiveRecord
{
    /**
     * @param array $data
     * @param string $formName
     * @return bool
     */
    public function load($data, $formName = '')
    {
        return parent::load($data, $formName);
    }

    /**
     * @return string
     */
    public function getId()
    {
        return $this->getAttribute('_id');
    }
}

models/Model.php
<?php
namespace app\models;

/**
 * Class Model
 * @package app\models
 */
class Model extends \yii\base\Model
{
    /**
     * @param array $data
     * @param string $formName
     * @return bool
     */
    public function load($data, $formName = '')
    {
        return parent::load($data, $formName);
    }
}

controllers/PageController.php
<?php

namespace app\controllers;

use app\models\page\Page;
use app\models\page\PageSearch;
use app\jobs\ParsingJob;
use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * PageController implements the CRUD actions for Page model.
 */
class PageController extends Controller
{
    /**
     * Lists all Page models.
     * @return mixed
     * @throws \Exception
     */
    public function actionIndex()
    {
        $params = Yii::$app->request->queryParams;
        $searchModel = new PageSearch();
        $dataProvider = $searchModel->search($params);

        return $this->render('index', [
            'searchModel'  => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new Page model.
     * @return mixed
     * @throws \yii\base\Exception
     */
    public function actionCreate()
    {
        $model = new Page();

        if ($model->load(Yii::$app->request->post(), null) && $model->save()) {
            /** @var yii\queue\redis\Queue $queue */
            $queue = Yii::$app->get('queue');

            $queue->push(new ParsingJob([
                'url'  => $model->url,
                'page' => $model
            ]));

            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Displays a single Page model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Delete Page model.
     * @param $id
     * @return mixed
     * @throws NotFoundHttpException
     * @throws \yii\db\StaleObjectException
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Page model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param $id
     * @return Page the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Page::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('Запрашиваемая страница не найдена');
        }
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use yii\web\Controller;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error'   => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class'           => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays users.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'parser', 'url' => ['/']],

        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>


<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/page/_form.php
<?php

use app\models\page\Page;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\page\Page */
/* @var $form yii\widgets\ActiveForm */

?>

<div class="transaction-form">
    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, Page::ATTR_URL)->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Спарсить',
            [
                'class' => 'btn btn-primary'
            ]) ?>
    </div>

    <?php ActiveForm::end(); ?>
</div>

views/page/_grid.php
<?php

use app\models\page\Page;
use yii\grid\GridView;
use yii\helpers\Html;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */
?>

<?php Pjax::begin() ?>
<?= GridView::widget([
    'dataProvider' => $dataProvider,
    'pager'        => [
        'linkContainerOptions'          => ['class' => 'page-item'],
        'linkOptions'                   => ['class' => 'page-link'],
        'disabledListItemSubTagOptions' => ['tag' => 'a', 'class' => 'page-link']
    ],
    'options'      => [
        'class' => 'table-responsive table-responsive-sm',
    ],
    'rowOptions'   => function ($model, $key, $index, $grid)
    {
        $class = $index % 2 ? 'odd' : 'even';

        return [
            'key'   => $key,
            'index' => $index,
            'class' => $class,
        ];
    },
    'tableOptions' => [
        'align' => 'center',
        'class' => 'table table-striped table-bordered table-hover text-center'
    ],
    'columns'      => [
        ['class' => 'yii\grid\SerialColumn'],
        [
            'attribute' => Page::ATTR_TITLE,
            'format'    => 'raw',
            'value'     => function ($data)
            {
                return Html::a($data->title, ['page/view', 'id' => $data->id]);
            },
        ],
        Page::ATTR_URL.':url',
        'createdAtFormatAdmin',
        'parsedAtFormatAdmin',
    ],
]);
?>

<?php Pjax::end() ?>

views/page/create.php
<?php

/* @var $this yii\web\View */
/* @var $model app\models\page\Page */

$this->title = 'Спарсить новую страницу';
$this->params['breadcrumbs'][] = ['label' => 'Список спарсенных страниц', 'url' => ['/pages']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="page-header row no-gutters py-4">
    <div class="col-12  text-sm-left mb-0">
        <h3 class="page-title"><?= $this->title ?></h3>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <?= $this->render('_form', [
            'model' => $model,
        ]) ?>
    </div>
</div>

views/page/index.php
<?php

/** @var $searchModel app\models\page\PageSearch */
/** @var $dataProvider yii\data\ActiveDataProvider */
/** @var $model app\models\page\Page */
/** @var $this yii\web\View */

$this->title = 'Список спарсенных страниц';
$this->params['breadcrumbs'][] = $this->title;

use yii\helpers\Html;
use yii\helpers\Url; ?>

<div class="page-header row no-gutters py-4">
    <div class="panel panel-default">
        <div class="panel-heading">
            <?= Html::a('Спарсить новую страницу', Url::to(['page/create']), ['class' => 'btn btn-primary']) ?>
        </div>
        <div class="panel-body">
            <?= $this->render('_grid', [
                'dataProvider' => $dataProvider,
                'searchModel'  => $searchModel
            ]); ?>
        </div>
    </div>
</div>

views/page/view.php
<?php

use app\models\file\File;
use app\models\page\Page;
use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\page\Page */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Страницы', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

$script = <<< JS
$(document).ready(function () {
    //при нажатии на ссылку, содержащую Thumbnail
    $('a.thumbnail').click(function(e) {
      //отменить стандартное действие браузера
      e.preventDefault();
      //присвоить атрибуту scr элемента img модального окна
      //значение атрибута scr изображения, которое обёрнуто
      //вокруг элемента a, на который нажал пользователь
      $('#image-modal .modal-body img').attr('src', $(this).find('img').attr('src'));
      //открыть модальное окно
      $("#image-modal").modal('show');
    });
    //при нажатию на изображение внутри модального окна
    //закрыть его (модальное окно)
    $('#image-modal .modal-body img').on('click', function() {
      $("#image-modal").modal('hide')
    });
});
JS;

$this->registerJs($script);
?>
<div class="page-view">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Удалить', ['delete', 'id' => (string)$model->id], [
            'class' => 'btn btn-danger',
            'data'  => [
                'confirm' => 'Вы уверены?',
                'method'  => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model'      => $model,
        'attributes' => [
            Page::ATTR_MONGO_ID,
            Page::ATTR_TITLE,
            Page::ATTR_URL.':url',
            Page::ATTR_CONTENT . ':html',
            [
                'attribute' => Page::ATTR_FILES,
                'format'    => 'raw',
                'value'     => function ($data)
                {
                    $images = '';
                    if ($data->files) {
                        $images .= '<div class="row">';
                        /** @var File $file */
                        foreach ($data->files as $file) {
                            $images .= "<div class='col-sm-6 col-md-4 col-lg-3'>
                                <a href='#' class='thumbnail'>
                                    <img src='{$file->getUrl()}' alt=''>
                                </a>
                            </div>";
                        }
                        $images .= '</div>';
                    }

                    return $images;
                },
            ],
            Page::ATTR_STATUS,
            'createdAtFormatAdmin',
            'parsedAtFormatAdmin',
        ],
    ]) ?>

    <?php if ($model->files): ?>
        <div class="modal fade" id="image-modal" tabindex="-1" role="dialog">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                    aria-hidden="true">×</span></button>
                        <div class="modal-title">Просмотр изображения</div>
                    </div>
                    <div class="modal-body">
                        <img class="img-responsive center-block" src="" alt="">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
                    </div>
                </div>
            </div>
        </div>
    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
parser